version: '3'
services:
  postgres:
    image: postgres:latest # use latest official postgres version
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=modelvpf

    ports:
      - '1234:5432'

    volumes:  # could contain the initial database structure and data
      - postgres-data-test:/var/lib/postgresql/test/ # persist data even if container shuts downvolumes


  modelvpf:
    build: .
    command: python -m test.test
    depends_on:
      - postgres

    volumes:
      - .:/app


volumes:
  postgres-data-test: # named volumes can be managed easier using docker-compose
