# MAKEFILE

# cd TFGinformatica
# python3 download.py

# cd path test

# docker-compose build
# docker-compose run modelvpf alembic upgrade head 
# docker-compose up

# #Teoricament s'haura executat el test

# Cnt + C

# cd path TFGInformatica
# docker-compose build
# docker-compose run modelvpf alembic upgrade head 
# docker-compose up

# #Teoricament s'haura executat el el codi principal

build-test:
	docker-compose -f docker-compose-test.yml up -d postgres 
	docker-compose -f docker-compose-test.yml exec postgres psql -U postgres -c 'CREATE DATABASE modelvpf;'
	docker-compose -f docker-compose-test.yml run modelvpf alembic upgrade head
	docker-compose -f docker-compose-test.yml down

updgrade-test-db:
	docker-compose -f docker-compose-test.yml run modelvpf alembic upgrade head

run-test:
	docker-compose -f docker-compose-test.yml run modelvpf
