"""Protein V - Protein H delete

Revision ID: 060b3224253f
Revises: 2e3cd21b196e
Create Date: 2021-04-26 18:10:59.667972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060b3224253f'
down_revision = '2e3cd21b196e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
