"""interaction solved

Revision ID: 0c17ca2dfcba
Revises: 4ec05fd0d6f1
Create Date: 2021-08-27 22:26:24.558059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c17ca2dfcba'
down_revision = '4ec05fd0d6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('interaction_idProteinH_fkey', 'interaction', type_='foreignkey')
    op.create_foreign_key(None, 'interaction', 'protein', ['idProteinH'], ['idProtein'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interaction', type_='foreignkey')
    op.create_foreign_key('interaction_idProteinH_fkey', 'interaction', 'function', ['idProteinH'], ['idFunction'])
    # ### end Alembic commands ###
