"""inaccessible proteins

Revision ID: 150468658027
Revises: 192a071c03d3
Create Date: 2021-08-26 00:03:22.879897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150468658027'
down_revision = '192a071c03d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inaccessible_protein',
    sa.Column('idProtein', sa.Integer(), nullable=False),
    sa.Column('codeUniprot', sa.String(length=15), nullable=False),
    sa.Column('codeString', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('idProtein'),
    sa.UniqueConstraint('codeString'),
    sa.UniqueConstraint('codeUniprot')
    )
    op.drop_constraint('interaction_idProteinH_fkey', 'interaction', type_='foreignkey')
    op.create_foreign_key(None, 'interaction', 'function', ['idProteinH'], ['idFunction'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interaction', type_='foreignkey')
    op.create_foreign_key('interaction_idProteinH_fkey', 'interaction', 'protein', ['idProteinH'], ['idProtein'])
    op.drop_table('inaccessible_protein')
    # ### end Alembic commands ###
