"""protein V - Protein H 

Revision ID: 1fdaf09cf212
Revises: 45cd24480154
Create Date: 2021-04-26 18:05:06.965615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fdaf09cf212'
down_revision = '45cd24480154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
