"""Create esquema bbdd

Revision ID: 24cb69ff2c31
Revises: 
Create Date: 2021-05-01 17:06:48.018279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24cb69ff2c31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('function',
    sa.Column('idFunction', sa.Integer(), nullable=False),
    sa.Column('codeGO', sa.String(length=15), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('aspect', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('idFunction'),
    sa.UniqueConstraint('codeGO')
    )
    op.create_table('model',
    sa.Column('idModel', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('idModel'),
    sa.UniqueConstraint('code')
    )
    op.create_table('species',
    sa.Column('idSpecies', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('taxonomy', sa.String(length=100), nullable=False),
    sa.Column('isVirus', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('idSpecies'),
    sa.UniqueConstraint('name')
    )
    op.create_table('protein',
    sa.Column('idProtein', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gene', sa.String(length=50), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('idSpecies', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idSpecies'], ['species.idSpecies'], ),
    sa.PrimaryKeyConstraint('idProtein'),
    sa.UniqueConstraint('code')
    )
    op.create_index('protein_idSpecies_index', 'protein', ['idSpecies'], unique=False)
    op.create_table('interaction',
    sa.Column('idProteinV', sa.Integer(), nullable=False),
    sa.Column('idProteinH', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idProteinH'], ['protein.idProtein'], ),
    sa.ForeignKeyConstraint(['idProteinV'], ['protein.idProtein'], ),
    sa.PrimaryKeyConstraint('idProteinV', 'idProteinH')
    )
    op.create_table('r_protein_function',
    sa.Column('idProtein', sa.Integer(), nullable=False),
    sa.Column('idFunction', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idFunction'], ['function.idFunction'], ),
    sa.ForeignKeyConstraint(['idProtein'], ['protein.idProtein'], ),
    sa.PrimaryKeyConstraint('idProtein', 'idFunction')
    )
    op.create_table('r_protein_modelvpf',
    sa.Column('idProtein', sa.Integer(), nullable=False),
    sa.Column('idModel', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('e_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['idModel'], ['model.idModel'], ),
    sa.ForeignKeyConstraint(['idProtein'], ['protein.idProtein'], ),
    sa.PrimaryKeyConstraint('idProtein', 'idModel')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('r_protein_modelvpf')
    op.drop_table('r_protein_function')
    op.drop_table('interaction')
    op.drop_index('protein_idSpecies_index', table_name='protein')
    op.drop_table('protein')
    op.drop_table('species')
    op.drop_table('model')
    op.drop_table('function')
    # ### end Alembic commands ###
