"""Protein V - Protein H 

Revision ID: 2e3cd21b196e
Revises: 1fdaf09cf212
Create Date: 2021-04-26 18:07:08.315907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3cd21b196e'
down_revision = '1fdaf09cf212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
