"""relation protein function

Revision ID: 4ec05fd0d6f1
Revises: 98cbf795d231
Create Date: 2021-08-27 22:19:51.736879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec05fd0d6f1'
down_revision = '98cbf795d231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
