"""add code String

Revision ID: 59099a0a9279
Revises: 7046f7fc7962
Create Date: 2021-07-28 18:12:49.191735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59099a0a9279'
down_revision = '7046f7fc7962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protein', sa.Column('codeString', sa.String(length=30), nullable=False))
    op.add_column('protein', sa.Column('codeUniprot', sa.String(length=15), nullable=False))
    op.drop_constraint('protein_code_key', 'protein', type_='unique')
    op.create_unique_constraint(None, 'protein', ['codeUniprot'])
    op.create_unique_constraint(None, 'protein', ['codeString'])
    op.drop_column('protein', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protein', sa.Column('code', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'protein', type_='unique')
    op.drop_constraint(None, 'protein', type_='unique')
    op.create_unique_constraint('protein_code_key', 'protein', ['code'])
    op.drop_column('protein', 'codeUniprot')
    op.drop_column('protein', 'codeString')
    # ### end Alembic commands ###
