"""inaccessible proteins

Revision ID: 591ccc1b766b
Revises: b15037a1d612
Create Date: 2021-08-26 00:26:51.446067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591ccc1b766b'
down_revision = 'b15037a1d612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
