"""protein interaction resoluted

Revision ID: 6e4348e997a0
Revises: 0c17ca2dfcba
Create Date: 2021-08-27 22:57:35.131748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4348e997a0'
down_revision = '0c17ca2dfcba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
