"""inaccessible proteins

Revision ID: 89c8c4a28f61
Revises: 591ccc1b766b
Create Date: 2021-08-26 00:30:43.523011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c8c4a28f61'
down_revision = '591ccc1b766b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
