"""Unique Constraint & index

Revision ID: 9e540b4e8d33
Revises: e296c39e9b0b
Create Date: 2021-04-27 00:17:31.844977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e540b4e8d33'
down_revision = 'e296c39e9b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'function', ['codeGO'])
    op.create_unique_constraint(None, 'model', ['code'])
    op.create_index('protein_idModel_index', 'protein', ['idModel'], unique=False)
    op.create_index('protein_idSpecies_index', 'protein', ['idSpecies'], unique=False)
    op.create_unique_constraint(None, 'protein', ['code'])
    op.create_unique_constraint(None, 'species', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'species', type_='unique')
    op.drop_constraint(None, 'protein', type_='unique')
    op.drop_index('protein_idSpecies_index', table_name='protein')
    op.drop_index('protein_idModel_index', table_name='protein')
    op.drop_constraint(None, 'model', type_='unique')
    op.drop_constraint(None, 'function', type_='unique')
    # ### end Alembic commands ###
