"""inaccessible proteins

Revision ID: b15037a1d612
Revises: 150468658027
Create Date: 2021-08-26 00:21:05.906822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15037a1d612'
down_revision = '150468658027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
