"""Table R_PROTEIN_MODELVPF

Revision ID: d394d83f51e5
Revises: 9e540b4e8d33
Create Date: 2021-04-27 23:51:06.779072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd394d83f51e5'
down_revision = '9e540b4e8d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('r_protein_modelvpf',
    sa.Column('idProtein', sa.Integer(), nullable=False),
    sa.Column('idModel', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['idModel'], ['model.idModel'], ),
    sa.ForeignKeyConstraint(['idProtein'], ['protein.idProtein'], ),
    sa.PrimaryKeyConstraint('idProtein', 'idModel')
    )
    op.drop_index('protein_idModel_index', table_name='protein')
    op.drop_constraint('protein_idModel_fkey', 'protein', type_='foreignkey')
    op.drop_column('protein', 'idModel')
    op.drop_column('protein', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protein', sa.Column('score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('protein', sa.Column('idModel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('protein_idModel_fkey', 'protein', 'model', ['idModel'], ['idModel'])
    op.create_index('protein_idModel_index', 'protein', ['idModel'], unique=False)
    op.drop_table('r_protein_modelvpf')
    # ### end Alembic commands ###
