"""Correct relation protein - function

Revision ID: e296c39e9b0b
Revises: 060b3224253f
Create Date: 2021-04-26 19:22:12.804327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e296c39e9b0b'
down_revision = '060b3224253f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
