"""protein interaction resoluted

Revision ID: f743cc4b1fe0
Revises: 6e4348e997a0
Create Date: 2021-08-29 02:12:08.788536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f743cc4b1fe0'
down_revision = '6e4348e997a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
